/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as GovernmentRouteImport } from './routes/government'
import { Route as IndustryRouteImport } from './routes/industry'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UniversityRouteImport } from './routes/university'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentRoute = GovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryRoute = IndustryRouteImport.update({
  id: '/industry',
  path: '/industry',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityRoute = UniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/citizen': typeof CitizenRoute
  '/government': typeof GovernmentRoute
  '/industry': typeof IndustryRoute
  '/login': typeof LoginRoute
  '/university': typeof UniversityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/citizen': typeof CitizenRoute
  '/government': typeof GovernmentRoute
  '/industry': typeof IndustryRoute
  '/login': typeof LoginRoute
  '/university': typeof UniversityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/citizen': typeof CitizenRoute
  '/government': typeof GovernmentRoute
  '/industry': typeof IndustryRoute
  '/login': typeof LoginRoute
  '/university': typeof UniversityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/citizen'
    | '/government'
    | '/industry'
    | '/login'
    | '/university'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/citizen'
    | '/government'
    | '/industry'
    | '/login'
    | '/university'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/citizen'
    | '/government'
    | '/industry'
    | '/login'
    | '/university'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  CitizenRoute: typeof CitizenRoute
  GovernmentRoute: typeof GovernmentRoute
  IndustryRoute: typeof IndustryRoute
  LoginRoute: typeof LoginRoute
  UniversityRoute: typeof UniversityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government': {
      id: '/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof GovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry': {
      id: '/industry'
      path: '/industry'
      fullPath: '/industry'
      preLoaderRoute: typeof IndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university': {
      id: '/university'
      path: '/university'
      fullPath: '/university'
      preLoaderRoute: typeof UniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  CitizenRoute: CitizenRoute,
  GovernmentRoute: GovernmentRoute,
  IndustryRoute: IndustryRoute,
  LoginRoute: LoginRoute,
  UniversityRoute: UniversityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
