/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccessRouteImport } from './routes/access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedCitizenRouteImport } from './routes/_authenticated/citizen'
import { Route as AuthenticatedGovernmentRouteImport } from './routes/_authenticated/government'
import { Route as AuthenticatedIndustryRouteImport } from './routes/_authenticated/industry'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedUniversityRouteImport } from './routes/_authenticated/university'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCitizenRoute = AuthenticatedCitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGovernmentRoute = AuthenticatedGovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndustryRoute = AuthenticatedIndustryRouteImport.update({
  id: '/industry',
  path: '/industry',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUniversityRoute = AuthenticatedUniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/citizen': typeof AuthenticatedCitizenRoute
  '/government': typeof AuthenticatedGovernmentRoute
  '/industry': typeof AuthenticatedIndustryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/university': typeof AuthenticatedUniversityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/citizen': typeof AuthenticatedCitizenRoute
  '/government': typeof AuthenticatedGovernmentRoute
  '/industry': typeof AuthenticatedIndustryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/university': typeof AuthenticatedUniversityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/access': typeof AccessRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/citizen': typeof AuthenticatedCitizenRoute
  '/_authenticated/government': typeof AuthenticatedGovernmentRoute
  '/_authenticated/industry': typeof AuthenticatedIndustryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/university': typeof AuthenticatedUniversityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/login'
    | '/signup'
    | '/citizen'
    | '/government'
    | '/industry'
    | '/profile'
    | '/settings'
    | '/university'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/login'
    | '/signup'
    | '/citizen'
    | '/government'
    | '/industry'
    | '/profile'
    | '/settings'
    | '/university'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/access'
    | '/login'
    | '/signup'
    | '/_authenticated/citizen'
    | '/_authenticated/government'
    | '/_authenticated/industry'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/university'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessRoute: typeof AccessRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/citizen': {
      id: '/_authenticated/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof AuthenticatedCitizenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/government': {
      id: '/_authenticated/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof AuthenticatedGovernmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/industry': {
      id: '/_authenticated/industry'
      path: '/industry'
      fullPath: '/industry'
      preLoaderRoute: typeof AuthenticatedIndustryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/university': {
      id: '/_authenticated/university'
      path: '/university'
      fullPath: '/university'
      preLoaderRoute: typeof AuthenticatedUniversityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCitizenRoute: typeof AuthenticatedCitizenRoute
  AuthenticatedGovernmentRoute: typeof AuthenticatedGovernmentRoute
  AuthenticatedIndustryRoute: typeof AuthenticatedIndustryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUniversityRoute: typeof AuthenticatedUniversityRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCitizenRoute: AuthenticatedCitizenRoute,
  AuthenticatedGovernmentRoute: AuthenticatedGovernmentRoute,
  AuthenticatedIndustryRoute: AuthenticatedIndustryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUniversityRoute: AuthenticatedUniversityRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessRoute: AccessRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
